# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-16 22:38
from __future__ import unicode_literals

import apps.proyects.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, null=True)),
                ('image', models.CharField(max_length=100, null=True, validators=[apps.proyects.validators.valid_extension_image])),
                ('product', models.CharField(max_length=100, null=True, validators=[apps.proyects.validators.valid_extension_project])),
                ('description', models.CharField(max_length=1000)),
                ('developer', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socialFacebook', models.CharField(max_length=100, null=True, validators=[apps.proyects.validators.valid_extension_social_facebook])),
                ('socialTwiter', models.CharField(max_length=100, null=True, validators=[apps.proyects.validators.valid_extension_social_twitter])),
                ('socialGoogle', models.CharField(max_length=100, null=True, validators=[apps.proyects.validators.valid_extension_social_google])),
                ('socialYoutube', models.CharField(max_length=100, null=True, validators=[apps.proyects.validators.valid_extension_social_youtube])),
                ('socialLinkedin', models.CharField(max_length=100, null=True, validators=[apps.proyects.validators.valid_extension_social_linkedin])),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='sociales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyects.Social'),
        ),
        migrations.AddField(
            model_name='products',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
