# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-22 06:38
from __future__ import unicode_literals

import apps.proyects.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyects', '0004_auto_20190522_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='socialFacebook',
            field=models.CharField(blank=True, default='none', max_length=100, null=True, validators=[apps.proyects.validators.valid_extension_social_facebook]),
        ),
        migrations.AlterField(
            model_name='social',
            name='socialGoogle',
            field=models.CharField(blank=True, default='none', max_length=100, null=True, validators=[apps.proyects.validators.valid_extension_social_google]),
        ),
        migrations.AlterField(
            model_name='social',
            name='socialLinkedin',
            field=models.CharField(blank=True, default='none', max_length=100, null=True, validators=[apps.proyects.validators.valid_extension_social_linkedin]),
        ),
        migrations.AlterField(
            model_name='social',
            name='socialTwiter',
            field=models.CharField(blank=True, default='none', max_length=100, null=True, validators=[apps.proyects.validators.valid_extension_social_twitter]),
        ),
        migrations.AlterField(
            model_name='social',
            name='socialYoutube',
            field=models.CharField(blank=True, default='none', max_length=100, null=True, validators=[apps.proyects.validators.valid_extension_social_youtube]),
        ),
    ]
