# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-08 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_limitproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limitcommunity',
            name='limitContent',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='limitproject',
            name='limitContent',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
