# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-29 00:23
from __future__ import unicode_literals

import apps.community.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_remove_community_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='image',
            field=models.CharField(max_length=250, null=True, validators=[apps.community.validators.valid_extension_image]),
        ),
        migrations.AlterField(
            model_name='community',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
